@startuml
'https://plantuml.com/sequence-diagram

scale 600 width

alt write than read

Thread_A -> j : write
Thread_Main --> j : read

else read than write


Thread_Main --> j : read
Thread_A -> j : write

end

@enduml