@startuml
'https://plantuml.com/sequence-diagram

scale 600 width

title How to Test?

alt operationA than operationB

Thread_A -> ClassUnderTest : operationA
Thread_B -> ClassUnderTest : operationB

else operationB than operationA


Thread_B -> ClassUnderTest : operationB
Thread_A -> ClassUnderTest : operationA

end

@enduml